# Generated by Django 2.2 on 2019-05-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20190511_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
        migrations.RemoveField(
            model_name='training',
            name='topic',
        ),
    ]
