# Generated by Django 2.2 on 2019-05-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20190511_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationitem',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='certificationitem',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='certificationitem',
            name='start_year',
        ),
    ]
