# Generated by Django 2.2 on 2019-05-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_resume_flickr'),
        ('curriculum', '0005_auto_20190511_1757'),
    ]

    operations = [
    ]
