# Generated by Django 2.2 on 2019-05-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190326_1754'),
        ('curriculum', '0006_merge_20190515_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='flickr',
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
