# Generated by Django 2.2 on 2019-05-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190326_1754'),
        ('curriculum', '0007_auto_20190516_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='training',
            name='resume',
        ),
        migrations.AddField(
            model_name='certificationitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='languageitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterUniqueTogether(
            name='certificationitem',
            unique_together={('certification', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='languageitem',
            unique_together={('language', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectitem',
            unique_together={('user', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='skillitem',
            unique_together={('skill', 'user')},
        ),
        migrations.RemoveField(
            model_name='certificationitem',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='languageitem',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='projectitem',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skillitem',
            name='resume',
        ),
    ]
