# Generated by Django 2.2 on 2019-05-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20190517_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='languageitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='accounts.User'),
        ),
    ]
