# Generated by Django 2.2 on 2019-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_auto_20190530_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='field_of_study',
            field=models.CharField(default=None, max_length=150, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='training',
            name='degree',
            field=models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd'), ('Others', 'Others')], max_length=1, verbose_name='level'),
        ),
    ]
