# Generated by Django 2.2 on 2019-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_auto_20190604_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='degree',
            field=models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd'), ('Others', 'Others')], max_length=150, verbose_name='level'),
        ),
    ]
